### ISSUE TITLE
/bin/sh: /var/subsonic/subsonic.sh: Permission denied

### ISSUE THREAD

**Issue by capitainabloc** [ghenry22/Subsonic_Synology#2]
Hi!
thanks a lot for this!
I followed carefully you explanations, but unfortunately, I have the `/bin/sh: /var/subsonic/subsonic.sh: Permission denied` when I try to launch Subsonic on my DSM6.

my passwd file is `subsonic:x:1027:100:Subsonic User:/var/subsonic:/bin/sh`
my files in /var/subsonic are chowned by subsonic:root, and executables are chmod +x
Any idea on a workaround?

Thanks

**Comment by ghenry22** [comment]
Sorry I haven't had an opportunity to test with DSM6 yet.  I will try to do so soon and provide an update.

**Comment by merkens11** [comment]
It would be great if you could provide an update. Thanks!

**Comment by ghenry22** [comment]
I havent had time to look at this much yet but I will pick it up soon and release an update for this project

**Comment by maria95posteonet** [comment]
ghenry22 - first of all, thanks again for all the great work you are doing with this!

As those of us who know know, Subsonic is without comparison the best for serious music fans on every parameter, sorting, ease of use, portability etc. But as we also know, getting it to work on a Synology NAS, peeerfect solution although it is, can be very difficult. Forum posts are endless and overflowing and suggested solutions complicated, time-consuming and often don't even last until the next reboot ....

It would be FANTASTIC if you made a proper, updated, secure Synology .spk for Subsonic. I for one would gladly pay (another) Subsonic life-time fee again for that!


But I'm getting carried away here -

I think I have a solution to this problem - of not retaining /etc/password edits - at least I've had a working Subsonic 6 on my NAS for the last several days :)

Used your guide

Plus this guy:
http://www.wakami.eu/2016/08/subsonic-on-synology-nas/

who says install ipkg, install ipkg bash, open /opt/bin/bash, and from THERE start Subsonic;

"

$/opt/bin/bash

Start subsonic:


$ cd /var/subsonic/standalone/
$ nohup ./subsonic.sh &

 the reason to install bash via ipkg is that the synology “bash” doesn’t support nohup, so Subsonic stops after you logout of your ssh session.

"


There is also this guys Youtube video, using your guide more-or-less:

https://www.youtube.com/watch?v=pRZiqqIURrw

That also worked for me, and no extra install of ipkg etc., but I got paranoid and deleted this solution because of the red-type "root user" warning Subsonic brings up as soon as you log in - surely just a minor tweak to avoid that but I really don't know enough about this.   

PLEASE dedicate your talents to keeping Synology users happy with an updating Subsonic package ... For the love of the music. And I have $150 dollars on the table at least like so many others I am 100% sure :)

**Comment by ghenry22** [comment]
I have completely rebuilt this as an installable spk package, tested and working on DSM6.0 so closing this
