### ISSUE TITLE
High memory usage even when idle

### ISSUE THREAD

**Issue by scienex** [ghenry22/Subsonic_Synology#26]
Hi,

I've been using this package for some weeks now. It all works smooth and simple - so I'm really content in that department.

There is one problem though: the memory usage of the Subsonic package on my DS218+ is very high - up to almost 500 MB when running idle. That is: I'm not streaming or even just browsing any music. I'm running DSM 6.2.1.

![capture](https://user-images.githubusercontent.com/11860069/48374054-f0eee780-e6c3-11e8-91b0-8bf01ce1460f.PNG)

Is there something I can do to get the package's memory usage down to an acceptable level? Or will I just have to live with this?

**Comment by ghenry22** [comment]
What is the total memory for your NAS? Subsonic picks a min and max memory setting based on the total memory of the system so this might need to be tweaked a bit for different models.

Making it too Low will make performance suffer on large libraries.

**Comment by scienex** [comment]
Thnx for your reply Ghenry22. The total memory is 2GB. Also, I have quite a large collection (70.000+ files). Anyway, if there's anything I could do myself, please let me know...

**Comment by MonsieurPoutounours** [comment]
@scienex You can tweak memory allocation for what you want, but be aware that setting it too low may cause performance issues.

* Activate SSH and login with admin account (Google "activate ssh synology" if you don't know how to do it. Admin account password is your built-in Administrator's one)
* Gain root access with : sudo su (you'll be asked to enter admin password again)
* Edit Subsonic's startup script with : vi /usr/syno/synoman/webman/3rdparty/subsonic/subsonic.sh
* Just before the line starting with SUBSONIC_HOME, add :
    SUBSONIC_INIT_MEMORY=XXX
    SUBSONIC_MAX_MEMORY=YYY
Replacing XXX par the initial amount of memory you want to allow to Subsonic, and YYY by the maximum amount of memory (in megabytes, like 128 for 128 MB)
(If you don't know about vi -the text editor-, you have to use the i key to enter insert mode - showing --INSERT-- on the bottom of the screen -, then adding the two lines, then Escape and type :wq to save and quit)
* This way, you'll force Subsonic to use the values you put in instead of picking it based on total RAM of your device.

Keep in mind you'll have to repeat this on each package upgrade, which will overwrite the file you modified.
This is a bit technical, but i hope you'll achieve it.

**Comment by scienex** [comment]
@MonsieurPoutounours thank you for this explanation! the holidays are the perfect time to try some tweaking ;)

**Comment by ghenry22** [comment]
@scienex I have added 2 new steps into the memory detection script so that it will allocate smaller steps for systems with 1gb and 2gb of memory available.  This will be included in the next release.

Until then hopefully the guide from @MonsieurPoutounours helps out!

**Comment by scienex** [comment]
thnx @genry22!
