### ISSUE TITLE
Can't access xxxx.subsonic.org from within the LAN 

### ISSUE THREAD

**Issue by gblavl** [ghenry22/Subsonic_Synology#39]
I have a premium Subsonic account and use the built-in Subsonic DDNS service (designated xxxx.subsonic.org) to remotely access Subsonic (6.1.6) on my Synology DS1819+ (DSM 6.2.3-25426 Update 2). It works perfectly--remotely. But that URL (http://xxxx.subsonic.org) doesn't revolve when I try to access the Subsonic server within my LAN. Within the LAN I have to use the IP address of the NAS (with port number for Subsonic). 

Previously when I ran Subsonic on a Windows 7 Pro machine, I could access Subsonic via the xxxx.subsonic.org address from within the LAN (on another computer or device). 

At an organization I work with we have the same setup on a DS1817+, and we have the same problem there. Everything works great remotely, but the yyyy.subsonic.org address won't resolve within the LAN. 

I'm extremely grateful for this Synology build of Subsonic. This is just a small irritation I can't yet resolve. Is there a trick to this I'm missing?

**Comment by ghenry22** [comment]
So the problem is generally with the router and the way that it processes traffic.

Because you are INSIDE the network and the subsonic.org address is OUTSIDE the network (it's your public IP), your traffic is trying to do a loop from INSIDE -> OUTSIDE -> INSIDE.

Routers will often refer to this as "Nat loopback" or "Nat hairpin".

If your router has a setting for this enable it and you should be all good.
