### ISSUE TITLE
port 4040 not responding

### ISSUE THREAD

**Issue by gerritbroekhuis** [ghenry22/Subsonic_Synology#8]
installed 6.0 on Synology NAS, but ip-address:4040 not responding.

What more should I do???

**Comment by ghenry22** [comment]
in the synology package manager there when you go to the subsonic package there should be a link called "view log" could you click that and then paste the contents into this issue ticket please?  That will help me to try and work out what is going wrong.

**Comment by gerritbroekhuis** [comment]
Hi Gaven,

Thanks for your time. This is all it says.. It shows my url with port 4040. I used the dowload package Subsonic601.spk (first I tried Subsonic60.spk). Same result with both.

[cid:image001.jpg@01D29BD3.383B2290]

Regards,

Gerrit Broekhuis

Van: Gaven Henry [mailto:notifications@github.com]
Verzonden: maandag 13 maart 2017 01:28
Aan: ghenry22/Subsonic_Synology <Subsonic_Synology@noreply.github.com>
CC: Gerrit Broekhuis <info@bah.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ghenry22/Subsonic_Synology] port 4040 not responding (#8)


in the synology package manager there when you go to the subsonic package there should be a link called "view log" could you click that and then paste the contents into this issue ticket please? That will help me to try and work out what is going wrong.

**Comment by ghenry22** [comment]
hi sorry the attachment hasn't come through, could you please upload it through the github web interface as a reply?  Maybe it has trouble processing it as it came as an email attachment.

**Comment by gerritbroekhuis** [comment]
![subsonic](https://cloud.githubusercontent.com/assets/26350396/23847699/f03b6ffa-07d3-11e7-968f-b60f52a40fd1.jpg)

**Comment by fieldhouse** [comment]
not sure why this was closed without explanation.  
 
I had a similar issue and determined that subsonic was only bound to TCP 4040 on IPv6.  IPv6 was disabled in the DSM interface.  Enabling IPv6 in DSM resolved the issue.

![image](https://cloud.githubusercontent.com/assets/2186295/24841384/100d0d1a-1d38-11e7-94c5-092cc3155dc5.png)

![image](https://cloud.githubusercontent.com/assets/2186295/24841383/061bbae0-1d38-11e7-9ddc-845984fe5a47.png)

![image](https://cloud.githubusercontent.com/assets/2186295/24841385/1b78da12-1d38-11e7-8848-4f81ad47c034.png)

**Comment by ghenry22** [comment]
Thanks for the feedback I will check options passed into java to ensure TCP v4 binding by default

**Comment by scienex** [comment]
> Enabling IPv6 in DSM resolved the issue.

Just curious (as I seem to have a really weird and annoying port forwarding issue - forwarding rules fail after each restart of the Subsonic package): how did you enable IPv6?

**Comment by ghenry22** [comment]
The package has been updated to bind to ipv4 so you shouldn’t need ipv6 at all, you could most likely disable ipv6 if it isn’t already.

What do you mean by forwarding rules fail?  Are you forwarding from your firewall to the Synology or something else?  Happy to try and help you work it out if I can.

**Comment by scienex** [comment]
Okay, in that case I don't understand what's going on. Since the option to automatically configere my router from the Subsonic site is not working (it says it fails to create the rule), I created a forwarding rule for port 4040 in Control Panel > External Acces > Router Configuration. If I save and then test it, it says OK. Whenever I close and then restart the Subsonic package (I close it sometimes because my girlfriend complains about the 'noise' the HD's on the NAS are making, and as I have mentioned in another thread, Subsonic uses quite a lot of memory), the port fowarding rule 'fails' and is removed from the list in my router.

Any settings in DSM I could tweak to stop this from happening? I don't think it's my modem, because it accepts all other port forwarding rules (either via UPnP or created by myself).

**Comment by MonsieurPoutounours** [comment]
@scienex You may try with setting a reverse proxy (Control panel > Applications portal > Reverse proxy). This way you can even have https support, and uPNP configuration may not fail.

**Comment by scienex** [comment]
@MonsieurPoutounours thank you for this suggestion! i'm going to look into that.

**Comment by scienex** [comment]
Christmas update because something totally weird happened: because of a power failure (caused by some lightbulb going berserk), my NAS turned off rather suddenly. When I turned it on, I forgot all about Subsonic and the port forwarding issue. 

Some hours later I turned on some music on my phone using the DSUB app - everything was working fine. Only when I noticed that this wasn't actually supposed to be the case did I think about the checking the port: it was all fine. And it is still fine after stopping the Subsonic apk and then running it again. 

Haven't got a clue how this is possible, but it's okay with me. After the next update, I'll just turn the thing off and on again ;)
